### ISSUE TITLE
RFE: Add registry should support sub-directories

### ISSUE THREAD

**Issue by parthaa** [projectatomic/docker#176]
It would be useful for projects like katello (https://github.com/Katello/katello) if the "--add-registry" commands supported sub directories as entry points.

On rhel for example 
```
# grep ADD_RE /etc/sysconfig/docker
# pull use the ADD_REGISTRY option to list a set of registries, each prepended
ADD_REGISTRY='--add-registry registry.access.redhat.com'
```
only accepts root names. If I say something like ```docker pull rhel``` I see that it tries to fetch it from ```registry.access.redhat.com/rhel``` before trying other registries. What would be ideal for a multi tenant registry facilitator like Katello would be something like
```
ADD_REGISTRY='--add-registry registry.access.redhat.com/<ORG>/<Environment>'
```

and now when the user does a ```docker pull rhel``` it  first checks for ```registry.access.redhat.com/<ORG>/<Environment>/rhel```

This way one can clearly separate registry namespaces .

**Comment by runcom** [comment]
Can't you achieve that with virtual hosts and have org.env.yourdomain.com? (since you have multiple instances of docker registry for each env/org) 

I understand the issue, I'm not getting why that can't be done in upper layers (virtual hosts)  and leave docker unchanged. 

There's more though, the slash isn't valid to be in there in your example because that's going confuse docker itself and treat everything after the slash as the image reference. The only way to do that is to have some sort of mirrors maybe but then you still have to have a plain subdomain to be used in docker pull.

**Comment by parthaa** [comment]
> Can't you achieve that with virtual hosts and have org.env.yourdomain.com? (since you have multiple instances of docker registry for each env/org)
@runcom Good point. I can look into a scheme that says *.registry.yourdomain.com will somehow translate to yourdomain.com/<org>/env/<staged-content> but wouldn't that mean that the customer and katello would have to somehow maintain a dns entry for each registry in an automated fashion.

**Comment by runcom** [comment]
The issue right now is that `docker pull yourdomain.com/<org>/env/<staged-content>/rhel` won't even work with docker.
The definition is
```                                      
 22 An image name is made up of slash-separated name components, optionally prefixed
 23 by a registry hostname
```
You can see paths aren't contemplated at all.
The only exception to that is `docker.io` which has historically translated that into the source code to something like `registry-1.docker.io` for their V1 version but that's just for them and supporting this kind of game (domain -> host+path) it's infeasible right now for this fork of docker.

> @runcom Good point. I can look into a scheme that says *.registry.yourdomain.com will somehow translate to yourdomain.com/<org>/env/<staged-content> but wouldn't that mean that the customer and katello would have to somehow maintain a dns entry for each registry in an automated fashion.

@parthaa the thing is, you still have to have to an hostname to work with Docker, there would be no other way as far as I can tell and you still need to setup DNS and virtual hosts to point to something.

**Comment by parthaa** [comment]
> The issue right now is that docker pull yourdomain.com/<org>/env/<staged-content>/rhel won't even work with docker.

:( . I saw https://github.com/docker/distribution/blob/master/docs/spec/api.md#overview where it seems to say (at least for v2) that ```If a repository name has two or more path components, they must be separated by a forward slash ("/")``` which led me along that path.  

Katello does ```yourdomain.com/<org>_<env>_<staged-content>_rhel``` changing the name of the repo which confused many. Even if we did ``` yourdomain.com/namespace``` and marked that as a registry, we could then say something like -> ```docker pull rhel``` would do docker pull ```yourdmain.com/namespace/rhel``` . Thought that might be more feasible ..

**Comment by runcom** [comment]
Right but unfortunately that's not going to work.

The only thing you can do is to use virtual hosts and dns.

**Comment by rhatdan** [comment]
Can we close this issue?

**Comment by runcom** [comment]
we can, I see no point in making our registry patch worst (and differ from upstream again) by supporting something like this when this can be achieved in upper layers in the stack (vhosts+dns).
