### ISSUE TITLE
Docker patch list is incredibly hard to find via Google

### ISSUE THREAD

**Issue by ncoghlan** [projectatomic/docker#177]
The patch list at "https://github.com/projectatomic/docker/blob/rhel7-1.10.3/README.md" appears to be entirely invisible to Google.

- "How does red hat docker differ from upstream" doesn't show it
- "Red hat docker github" doesn't show it (it doesn't even show this repo)
- "project atomic docker github" doesn't show it (it doesn't even show this repo)
- "project atomic docker patch list" doesn't show it

Even knowing the page existed, I was unable to find a search query that would give it to me - I eventually managed to find the right sequence of words that brought it back up in my Firefox site history.

Would it be possible to add an index page to projectatomic.org with some explanatory text that points to the relevant README files in the GitHub repo? Search engines might have an easier time with that than they do with a branch of a fork of the main docker repo.

**Comment by rhatdan** [comment]
Should we just make the master branch of projectatomic/docker have the patches?

**Comment by rhatdan** [comment]
@jberkus Josh could we add a link to projectatomic.org for this?

**Comment by ncoghlan** [comment]
Including the README on the master branch would at least make it appear when folks browse to "projectatomic/docker" on GitHub, but I think the way GitHub have their canonical URLs set up (or else the way the Googlebot specifically processes GitHub forks) mean that forks still tend not to show up in Google results (see the 3rd query I tried above).

**Comment by jberkus** [comment]
@rhatdan funny, I was just about to ask you to do a blog post on this.  I think a blog post, plus a projectatomic.io page, would be a good start.

In the medium term, we should have a full set of "docs" for the Red Hat changes.

**Comment by rhatdan** [comment]
Yes I will write a blog on this when I get back from PTO.  Next week.

**Comment by ncoghlan** [comment]
Following Dan's post at http://www.projectatomic.io/blog/2016/08/docker-patches/, I'm happy to report "red hat docker patches" now returns http://www.projectatomic.io/docs/docker_patches/ as the second link :)

"red hat docker differences" and "red hat docker changes" results will presumably take longer to improve, but I think this can be considered resolved now.
