### ISSUE TITLE
Docker cli doesn't honor DOCKER_CERT_PATH

### ISSUE THREAD

**Issue by wied03** [projectatomic/docker#197]
The main Docker issue (https://github.com/docker/docker/issues/25986) is asserting this is a problem with the CentOS build.

**Comment by runcom** [comment]
I'll try to reproduce

**Comment by runcom** [comment]
@wied03 pretty sure it's a misconfiguration on your side ;) OR it has been fixed in the last releases

(note I'm using Fedora here but the source of Docker still comes from this repository and I rebuilt the RHEL branch which is used for centos)
```
16:30:37 [~/cert-docker-test] ll client 
total 20K
-rw-rw-r--. 1 amurdaca amurdaca 2.0K Sep 23 16:29 ca.pem
-rw-rw-r--. 1 amurdaca amurdaca 1.8K Sep 23 16:18 cert.pem
-rw-rw-r--. 1 amurdaca amurdaca 1.6K Sep 23 16:18 client.csr
-rw-rw-r--. 1 amurdaca amurdaca   30 Sep 23 16:17 extfile.cnf
-rw-rw-r--. 1 amurdaca amurdaca 3.2K Sep 23 16:17 key.pem
16:30:39 [~/cert-docker-test] env | grep DOCKER
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/home/amurdaca/cert-docker-test/client
16:30:48 [~/cert-docker-test] docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-52.git8b7fa4a.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      8b7fa4a/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-52.git8b7fa4a.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      8b7fa4a/1.10.3
 Built:           
 OS/Arch:         linux/amd64
16:30:55 [~/cert-docker-test] export DOCKER_CERT_PATH=/home/amurdaca/cert-docker-test/doesntexist 
16:31:11 [~/cert-docker-test] docker version                                                     
Could not read CA certificate "/home/amurdaca/cert-docker-test/doesntexist/ca.pem": open /home/amurdaca/cert-docker-test/doesntexist/ca.pem: no such file or directory
```

**Comment by wied03** [comment]
Maybe, but it's super easy to reproduce with the latest CentOS Atomic. What docker RPM version are you using?

```
[brady@virtualweez ~]$ export DOCKER_TLS_VERIFY=1
[brady@virtualweez ~]$ DOCKER_CERT_PATH=/home/doesntexist docker version
Could not read CA certificate "/etc/docker/ca.pem": open /etc/docker/ca.pem: no such file or directory
[brady@virtualweez ~]$ rpm -q docker
docker-1.10.3-46.el7.centos.10.x86_64
[brady@virtualweez ~]$ 
```

**Comment by runcom** [comment]
> CentOS Atomic

let me spin up a RHEL atomic, I'll get back asap

**Comment by runcom** [comment]
@wied03 figured - can you please edit `/etc/sysconfig/docker` and remove the lines with:
```
[...]
DOCKER_CERT_PATH=/etc/docker
[...]
```
everythink should work then but be aware we did that for some reasons - more background and links at https://bugzilla.redhat.com/show_bug.cgi?id=1169593

**Comment by wied03** [comment]
Should have thought to look there!

**Comment by runcom** [comment]
> I should have thought to look there!

:smile:

**Comment by wied03** [comment]
What's odd to me is that the docker client is adhering to those sysconfig settings. I would have expected only the daemon to do that.

**Comment by runcom** [comment]
> What's odd to me is that the docker client is adhering to those sysconfig settings. I would have expected only the daemon to do that.

in docker 1.10 both the daemon and the client are called `docker` and when executed it'll read stuff from the `/etc/sysconfig/docker` file. It works like this for every binary - it's just a case daemon and client are called the same and so `/etc/sysconfig/docker` is applied to both.

**Comment by wied03** [comment]
Ohh yeah I forgot about that as well. Well maybe the recommendation for now until the newer split client/daemon is that if you need to have a different cert directory for client and server, remove that setting from sysconfig and supply the daemon side env variable via systemd and the client side via whatever means.
