### ISSUE TITLE
Error when pulling images from Quay.io 

### ISSUE THREAD

**Issue by wallrj** [projectatomic/docker#214]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:         1.12.3
 API version:     1.24
 Package version: docker-common-1.12.3-9.git47e22f2.fc25.x86_64
 Go version:      go1.7.3
 Git commit:      47e22f2/1.12.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.3
 API version:     1.24
 Package version: docker-common-1.12.3-9.git47e22f2.fc25.x86_64
 Go version:      go1.7.3
 Git commit:      47e22f2/1.12.3
 Built:           
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
$ docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 55
Server Version: 1.12.3
Storage Driver: btrfs
 Build Version: Btrfs v4.6.1
 Library Version: 101
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp
Kernel Version: 4.8.8-300.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.38 GiB
Name: drax
ID: I42H:Y2Z6:LECC:L7YW:ORMV:3OZE:7ZCA:QIYH:UPLE:R76L:AXGI:QX6O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ dnf info docker
Last metadata expiration check: 6 days, 19:01:02 ago on Wed Nov 23 22:14:37 2016.
Installed Packages
Name        : docker
Arch        : x86_64
Epoch       : 2
Version     : 1.12.3
Release     : 9.git47e22f2.fc25
Size        : 60 M
Repo        : @System
From repo   : updates
Summary     : Automates deployment of containerized applications
URL         : https://github.com/projectatomic/docker
License     : ASL 2.0
Description : Docker is an open-source engine that automates the deployment of any
            : application as a lightweight, portable, self-sufficient container that will
            : run virtually anywhere.
            : 
            : Docker containers can encapsulate any payload, and will run consistently on
            : and between virtually any server. The same container that a developer builds
            : and tests on a laptop will run at scale, in production*, on VMs, bare-metal
            : servers, OpenStack clusters, public instances, or combinations of the above.


```

```
$ cat /etc/os-release 
NAME=Fedora
VERSION="25 (Workstation Edition)"
ID=fedora
VERSION_ID=25
PRETTY_NAME="Fedora 25 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:25"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=25
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=25
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

**Steps to reproduce the issue:**
1. `docker pull quay.io/pypa/manylinux1_x86_64`

```
$ docker pull quay.io/pypa/manylinux1_x86_64
Using default tag: latest
Trying to pull repository quay.io/pypa/manylinux1_x86_64 ... 
json: cannot unmarshal bool into Go value of type docker.APIErrors

```

2. The ubuntu:1604 image from DockerHub works fine

```
$ docker pull ubuntu:16.04
Trying to pull repository docker.io/library/ubuntu ... 
sha256:3b64c309deae7ab0f7dbdd42b6b326261ccd6261da5d88396439353162703fb5: Pulling from docker.io/library/ubuntu
af49a5ceb2a5: Pull complete 
8f9757b472e7: Pull complete 
e931b117db38: Pull complete 
47b5e16c0811: Pull complete 
9332eaf1a55b: Pull complete 
Digest: sha256:3b64c309deae7ab0f7dbdd42b6b326261ccd6261da5d88396439353162703fb5
Status: Downloaded newer image for docker.io/ubuntu:16.04
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by runcom** [comment]
@wallrj `quay.io` is serving docker registry V1 API. This docker has a feature enabled by default: signatures verification. Signatures verification does not work against V1 registries. There is a knob you can add to your `/etc/sysconfig/docker` in order to disable this feature and pull again from `quay.io`. The option to set is `--signature-verification=false`.

**Comment by wallrj** [comment]
@runcom Thanks for the fast reply. `--signature-verification=false` worked.

It's a shame Docker doesn't give a more meaningful error message ☹️

**Comment by runcom** [comment]
> It's a shame Docker doesn't give a more meaningful error message

good point, let me take a look at the code to see if I can show a proper error message.

**Comment by josephschorr** [comment]
@runcom: Actually, we serve both V2 and V1, converting between them automatically if pushed by one version and pulled by another. I'm not sure why your Docker binary is using the V1 protocol, as the majority of our requests served are done via V2 at this point. Are there any custom protocol checks outside of the vanilla Docker version?

**Comment by runcom** [comment]
> @runcom: Actually, we serve both V2 and V1, converting between them automatically if pushed by one version and pulled by another. I'm not sure why your Docker binary is using the V1 protocol, as the majority of our requests served are done via V2 at this point. Are there any custom protocol checks outside of the vanilla Docker version?

@josephschorr we saw that `docker pull quay.io/pypa/manylinux1_x86_64` isn't found on the V2 registry, and you can download it with docker because if an image isn't found in V2 - it falls back to V1 and you can pull it successfully from V1. The difference here is that our docker uses a custom library to do image signature verification and it does only support V2 at this point (erroring out with the above error).

**Comment by runcom** [comment]
I'll investigate further though.

**Comment by josephschorr** [comment]
@runcom: Except we don't fallback. If you pull via V2, you get V2. We convert to V2 in real-time if the image was only pushed via V1. Looking at the logs, I just pulled the image via V2 on my local machine.

**Comment by runcom** [comment]
@josephschorr right, still looking, we may probably have a bug somewhere

**Comment by runcom** [comment]
@josephschorr thanks a lot for chiming in - found the root cause https://github.com/containers/image/pull/176 (tested our docker and it's indeed now pulling from V2 as you said) - thanks again.

**Comment by rhatdan** [comment]
Excellent.  Thanks @josephschorr

**Comment by josephschorr** [comment]
Glad we were able to find the cause!
