### ISSUE TITLE
Is it possible to pull https://github.com/moby/moby/pull/33472 to fix a memory leak in the current 1.12.6 (and probably all) version of docker

### ISSUE THREAD

**Issue by fortinj66** [projectatomic/docker#252]
This issue is identified  in:
https://github.com/moby/moby/issues/32711
and solved (hopefully) in:
https://github.com/moby/moby/pull/33472

All 1.12.5 and 1.12.6 versions (RedHat/Centos and vanilla) seem to be affected.  This issues causes large dockerd memory in Openghift origin requiring at least weekly restarts of Docker... 

Regards,
--John

**Comment by runcom** [comment]
I'll backport it yeah

**Comment by fortinj66** [comment]
Awesome!!

**Comment by runcom** [comment]
backported.

**Comment by fortinj66** [comment]
Thanks!  

When would this likely show up in the Centos repos for download/install?

Unfortunately, I have been unable to get a working RPM built from the projectatomic sources...

--John
