### ISSUE TITLE
Backport: Enable deferred removal and deferred deletion by default

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker#261]
Recently upstream committed a patch to enable deferred removal and deferred deletion by default. May be its a good idea to carry that patch.

https://github.com/moby/moby/pull/33698/commits/0dc1a80565d522fc2cc7c65c3ad2d8ed83aeaf0f

**Comment by rhvgoyal** [comment]
@runcom Would you be in a position to backport this one?

**Comment by runcom** [comment]
backported to 1.12.6, 1.13.1 and 1.13.1-rhel

**Comment by rhvgoyal** [comment]
@runcom wow, that was quick.  thanks.
