### ISSUE TITLE
Backport: Fixes for supporting deferred removal enabled but deferred deletion disabled

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker#266]
We need to backport following PR. This enables supporting when deferred removal is enabled but deferred deletion is disabled. 

https://github.com/moby/moby/pull/33877

**Comment by rhvgoyal** [comment]
cc @runcom

**Comment by runcom** [comment]
Backported @rhvgoyal @rhatdan

**Comment by rhvgoyal** [comment]
Thanks @runcom
