### ISSUE TITLE
Volume mounting problem using docker-latest and SELinux

### ISSUE THREAD

**Issue by TerenceJohnson** [projectatomic/docker#268]
After switching to docker-latest in Atomic 7.1706 mounting NFS volumes fails with the following SELinux error:

docker volume create --driver local --opt type=nfs --opt o=addr=192.168.0.12,ro --opt device=:/mnt/files/ --name files
docker service update --mount-add type=volume,source=files,target=/mnt/files test

```
Jul 26 13:45:50 docker-test-a dockerd-latest: time="2017-07-26T13:45:50.291773263-04:00" level=error msg="fatal task error" error="SELinux relabeling of  is not allowed: \"no such file or directory\"" module="node/agent/taskmanager" task.id=mihxbfnpvgzcc4s5u6uuxgbia
Jul 26 13:45:52 docker-test-a dockerd-latest: time="2017-07-26T13:45:52.769107307-04:00" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc2\nspec: 1.0.0-rc2-dev\n"
Jul 26 13:45:52 docker-test-a dockerd-latest: time="2017-07-26T13:45:52.769150480-04:00" level=warning msg="failed to retrieve docker-init version"
```
This was working with docker 1.12.6 but I found that version did not automatically rejoin a swarm after a host reboot.

**Comment by rhatdan** [comment]
We just committed a fix that should solve this issue.

**Comment by TerenceJohnson** [comment]
Thank you. Please could you post a link to that commit so that I can figure out how to get this into my test hosts?

**Comment by rhatdan** [comment]
I believe this version of docker has the fix.
https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=575326
docker-1.12.6-48.git0fdc778.el7
@runcom could you verify?  This is about the runc patch which reverts back the error return code on EINVAL.

**Comment by runcom** [comment]
@rhatdan nope, that package hasn't the fix for this issue as the docker-runc built in that package doesn't contain the latest commit in https://github.com/projectatomic/runc/commits/docker-1.12.6. We need this commit of docker-runc from projectatomic/runc https://github.com/projectatomic/runc/commit/31a9f6e22729606814e9bcbcf9eeebc1887527cb, @lsm5 could you rebuild docker using that commit for docker-runc in the spec?

**Comment by rhatdan** [comment]
We need this fix for 7.4.1

**Comment by lsm5** [comment]
@runcom could you include that patch on docker-1.13.1-rhel as well, since the issue seems to be for docker-latest?

**Comment by runcom** [comment]
@lsm5 done, that patch is in 1.13.1 and 1.13.1-rhel

**Comment by Raghuveer123** [comment]
any latest update on this issue?

**Comment by rhatdan** [comment]
@Raghuveer123 I would guess this is fixed.  Reopen if it is not.

**Comment by rhatdan** [comment]
I thought the patch that @runcom merged in July 28th.
