### ISSUE TITLE
Backport fix for overlay redirect_dir=on

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker#275]
We probably will need to backport following so that docker can deal with kernel having redirect_dir=on for overlayfs.

https://github.com/moby/moby/pull/34342

**Comment by rhvgoyal** [comment]
cc @runcom @rhatdan

**Comment by rhatdan** [comment]
How big of a back port is this going to be?  We need to grab this functionality for containers/storage though

**Comment by rhatdan** [comment]
@nalind WDYT

**Comment by runcom** [comment]
Backported to 1.12.6, 1.13.1 and 1.13.1-rhel

**Comment by rhvgoyal** [comment]
thanks @runcom
