### ISSUE TITLE
 Prevent panic if exec process dies before sync channel is created

### ISSUE THREAD

**Issue by free2k** [projectatomic/docker#322]
**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.mt20180816.git13d3ca3.el7.centos.x86_64
 Go version:      go1.7.5
 Git commit:      13d3ca3/1.13.1
 Built:           Thu Aug 16 07:02:16 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.mt20180816.git13d3ca3.el7.centos.x86_64
 Go version:      go1.7.5
 Git commit:      13d3ca3/1.13.1
 Built:           Thu Aug 16 07:02:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `docker info`:**

```
Containers: 95
 Running: 88
 Paused: 0
 Stopped: 7
Images: 346
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: dockervg-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 270.8 GB
 Data Space Total: 1.947 TB
 Data Space Available: 1.676 TB
 Metadata Space Used: 78.2 MB
 Metadata Space Total: 16.98 GB
 Metadata Space Available: 16.9 GB
 Thin Pool Minimum Free Space: 194.7 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version: 13d3ca3fcd69add948a295eb337a4bad27705f27 (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: e9c345b3f906d5dc5e8100b05ce37073a811c74a (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: 5b117de7f824f3d3825737cf09581645abbe35d4 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-693.mt20180403.47.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 48
Total Memory: 377.6 GiB
Name: gh-hulk-k8s-ep404.gh.sankuai.com
ID: SPRK:TNQH:DY6F:7H5V:IDOG:2Q2H:UN5Y:VXWV:CW4Z:D6ZS:WUKK:VQH2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://127.0.0.1:65001
 registry-hulk.sankuai.com
Live Restore Enabled: true
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
This problem is not necessarily the case, but two have been found in more than 100 devices. I think it's related to concurrent stop and exec.

**Describe the results you received:**
`Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: time="2018-09-11T19:32:48.729036755+08:00" level=warning msg="Ignoring StateExitProcess for {{exit-process 0 137 b8568074406f2e634dcf70e3a48e17d40533ef60db056c0425b71d87a4597660} false} but no exec command found"
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: panic: close of nil channel
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: goroutine 3431050 [running]:
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: panic(0x84f9e0, 0x936c30)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/panic.go:540 +0x45e fp=0xc4203e0eb0 sp=0xc4203e0e08 pc=0x42d10e
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.closechan(0x0)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/chan.go:315 +0x2df fp=0xc4203e0f10 sp=0xc4203e0eb0 pc=0x405fbf
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: github.com/docker/containerd/supervisor.(*Supervisor).execExit.func1(0xc42035ea20, 0xc4200ab860, 0x0)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /root/code/docker/pkg/docker/build-rpm/BUILD/docker-13d3ca3fcd69add948a295eb337a4bad27705f27/_build/src/github.com/docker/containerd/supervisor/exit.go:92 +0x10e fp=0xc4203e0fc8 sp=0xc4203e0f10 pc=0x7c026e
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.goexit()
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4203e0fd0 sp=0xc4203e0fc8 pc=0x45e761
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: created by github.com/docker/containerd/supervisor.(*Supervisor).execExit
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /root/code/docker/pkg/docker/build-rpm/BUILD/docker-13d3ca3fcd69add948a295eb337a4bad27705f27/_build/src/github.com/docker/containerd/supervisor/exit.go:83 +0x15f
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: goroutine 1 [chan receive, 27843 minutes]:
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.gopark(0x8ff0b8, 0xc4201925f8, 0x8e288f, 0xc, 0xc4204c3717, 0x3)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/proc.go:287 +0x12c fp=0xc4204c37a0 sp=0xc4204c3770 pc=0x42f20c
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.goparkunlock(0xc4201925f8, 0x8e288f, 0xc, 0x17, 0x3)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/proc.go:293 +0x5e fp=0xc4204c37e0 sp=0xc4204c37a0 pc=0x42f2fe
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.chanrecv(0xc4201925a0, 0xc4204c39c8, 0x825e01, 0x935ad0)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/chan.go:506 +0x304 fp=0xc4204c3890 sp=0xc4204c37e0 pc=0x406354
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.chanrecv2(0xc4201925a0, 0xc4204c39c8, 0x0)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/chan.go:393 +0x2b fp=0xc4204c38c0 sp=0xc4204c3890 pc=0x40603b
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: main.daemon(0xc4201f8280, 0xd, 0x0)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /root/code/docker/pkg/docker/build-rpm/BUILD/docker-13d3ca3fcd69add948a295eb337a4bad27705f27/containerd-296f1f80d6c6a83cc625163f863e53d3287328ee/containerd/main.go:197 +0x5eb fp=0xc4204c3a48 sp=0xc4204c38c0 pc=0x7d171b
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: main.main.func2(0xc4201f8280)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /root/code/docker/pkg/docker/build-rpm/BUILD/docker-13d3ca3fcd69add948a295eb337a4bad27705f27/containerd-296f1f80d6c6a83cc625163f863e53d3287328ee/containerd/main.go:150 +0x2b fp=0xc4204c3a80 sp=0xc4204c3a48 pc=0x7d2ddb
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: github.com/codegangsta/cli.(*App).Run(0xc4201f8140, 0xc4200100e0, 0xe, 0xe, 0x0, 0x0)
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /root/code/docker/pkg/docker/build-rpm/BUILD/docker-13d3ca3fcd69add948a295eb337a4bad27705f27/containerd-296f1f80d6c6a83cc625163f863e53d3287328ee/vendor/src/github.com/codegangsta/cli/app.go:192 +0x90b fp=0xc4204c3ee8 sp=0xc4204c3a80 pc=0x76b83b
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: main.main()
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /root/code/docker/pkg/docker/build-rpm/BUILD/docker-13d3ca3fcd69add948a295eb337a4bad27705f27/containerd-296f1f80d6c6a83cc625163f863e53d3287328ee/containerd/main.go:154 +0x199 fp=0xc4204c3f80 sp=0xc4204c3ee8 pc=0x7d0ee9
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.main()
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/proc.go:195 +0x226 fp=0xc4204c3fe0 sp=0xc4204c3f80 pc=0x42ed56
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: runtime.goexit()
Sep 11 19:32:48 gh-hulk-k8s-ep404.gh.sankuai.com dockerd-current[147917]: /usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4204c3fe8 sp=0xc4204c3fe0 pc=0x45e761`

**Describe the results you expected:**
The docker-containerd-current process runs normally and does not exit

**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/moby/moby/issues/30469
I think this is caused by this bug, but I found that you did not fix this bug.

**Comment by runcom** [comment]
Fixed in docker-1.13.1-rhel and docker-1.13.1
