### ISSUE TITLE
support update device-read-bps and device-write-bps

### ISSUE THREAD

**Issue by free2k** [projectatomic/docker#378]
![image](https://user-images.githubusercontent.com/14852402/104316813-fe0ff700-5517-11eb-8729-8ea7b89c7411.png)
   Why does docker update not support the update of these parameters？《--device-read-bps      --device-read-iops   --device-write-bps    --device-write-iops》

**Comment by rhatdan** [comment]
This is pretty much a archived project at this point.  Questions should go to the upstream moby project or better yet start using podman and see if it works the way you want.
